
--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: ORACLE Version: 8

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'C:\Users\Marcin\Desktop\the-only-erd-we-need-for-ead.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE Employee CASCADE CONSTRAINTS;

DROP TABLE Project CASCADE CONSTRAINTS;

DROP TABLE Client CASCADE CONSTRAINTS;

DROP TABLE Contact CASCADE CONSTRAINTS;

DROP TABLE Manager CASCADE CONSTRAINTS;

DROP TABLE Role CASCADE CONSTRAINTS;

DROP TABLE ProjectTeamMember CASCADE CONSTRAINTS;

DROP TABLE EmployeeRoles CASCADE CONSTRAINTS;

DROP TABLE SubordinateEmployee CASCADE CONSTRAINTS;

DROP TABLE ManagerRole CASCADE CONSTRAINTS;

DROP TABLE ProjectContact CASCADE CONSTRAINTS;

DROP TABLE ProjectHours CASCADE CONSTRAINTS;

DROP TABLE ProjectTask CASCADE CONSTRAINTS;

DROP TABLE TaskAssignedTo CASCADE CONSTRAINTS;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------
