CREATE OR REPLACE TRIGGER UPDATE_TOTAL_BILLHOURS
AFTER UPDATE OR INSERT ON PROJECTHOURS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW

DECLARE
  TotalBillHoursForProject Project.CurrentBillableHours%type;

BEGIN
    SELECT SUM(HOURSWORKED)
    INTO TotalBillHoursForProject
    FROM PROJECTHOURS WHERE FK_PROJECTID = :NEW.FK_PROJECTID;

    UPDATE PROJECT SET (PROJECT.CURRENTBILLABLEHOURS) = TotalBillHoursForProject WHERE PROJECTID = :NEW.FK_PROJECTID;

END;
    
